module.exports = {
  apps: [{
    name: 'stock-app',
    script: 'npm',
    args: 'start',
    cwd: '/var/www/stock-management',
    instances: 1,
    exec_mode: 'fork',
    env: {
      DATABASE_URL: 'postgresql://stockapp:SMT2025@localhost:5432/stock_management?schema=public',
      NODE_ENV: 'production',
      NEXT_PUBLIC_API_URL: 'https://172.17.5.199',
      SESSION_SECRET: 'przFeJuWQFfZ15KGJ1+atTmeNfPH9IrlMiTVSXqPG08=',
      JWT_SECRET: 'Pq5NWU4IuduKa4qTBP7kU/noGGXhzp8eoQLpDy04Sd8=',
      SMTP_HOST: 'smtp.gmail.com',
      SMTP_PORT: '587',
      SMTP_SECURE: 'false',
      SMTP_USER: 'your-email@gmail.com',
      SMTP_PASSWORD: 'your-app-password',
      SMTP_FROM_EMAIL: 'noreply@172.17.5.199',
      SMTP_FROM_NAME: 'Monetique Tunisie - Gestion de Stocks',
      NOTIFICATIONS_ENABLED: 'true',
      NOTIFICATIONS_LOW_STOCK_ALERTS: 'true',
      NOTIFICATIONS_MOVEMENT_NOTIFICATIONS: 'true',
      NOTIFICATIONS_USER_ACTIVITY_ALERTS: 'true',
      NOTIFICATIONS_LOW_STOCK_THRESHOLD: '10',
      NOTIFICATIONS_CRITICAL_STOCK_THRESHOLD: '5',
      NOTIFICATIONS_EMAIL_NOTIFICATIONS: 'true',
      NOTIFICATIONS_IN_APP_NOTIFICATIONS: 'true',
    },
    error_file: '/root/.pm2/logs/stock-app-error.log',
    out_file: '/root/.pm2/logs/stock-app-out.log',
    log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    merge_logs: true,
    autorestart: true,
    watch: false,
    max_memory_restart: '1G'
  }]
};
